site_name: prefect-alert
site_url: https://khuyentran1401.github.io/prefect-alert
repo_url: https://github.com/khuyentran1401/prefect-alert
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: img/favicon.ico
  palette:
    primary: blue
    accent: blue
  icon:
    repo: fontawesome/brands/github
  logo:
    img/prefect-logo-mark-solid-white-500.png
  font:
    text: Inter
    code: Source Code Pro
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
    - pymdownx.tabbed
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: True
            show_bases: True
            show_signature: False
            heading_level: 1
watch:
    - prefect_alert/
    - README.md

nav:
    - Home: index.md
    - Alert Decorator: alert.md